package msgkey

const (
	ApiAccessDenied                            = "API_ACCESS_DENIED"
	TokenFailed                                = "TOKEN_FAILED"
	TokenExpired                               = "TOKEN_EXPIRED"
	MissingOrMalformedJwt                      = "MISSING_OR_MALFORMED_JWT"
	RequestFailed                              = "REQUEST_FAILED"
	RequestValueInvalid                        = "REQUEST_VALUE_INVALID"
	FailedToReadClusterInfo                    = "FAILED_TO_READ_CLUSTER_INFO"
	ClusterNotFound                            = "CLUSTER_NOT_FOUND"
	ClusterNotFoundInKarmada                   = "CLUSTER_NOT_FOUND_IN_KARMADA"
	ClusterAlreadyRegistered                   = "CLUSTER_ALREADY_REGISTERED"
	ClusterAlreadyRegisteredInKarmada          = "CLUSTER_ALREADY_REGISTERED_IN_KARMADA"
	ResourceUpdateFailed                       = "RESOURCE_UPDATE_FAILED"
	ResourceUpdateSuccess                      = "RESOURCE_UPDATE_SUCCESS"
	ResourceDeleteFailed                       = "RESOURCE_DELETE_FAILED"
	ResourceDeletionCompleted                  = "RESOURCE_DELETE_COMPLETED"
	ResourceCreateFailed                       = "RESOURCE_CREATE_FAILED"
	ResourceCreateSuccess                      = "RESOURCE_CREATE_SUCCESS"
	ResourceNotFound                           = "RESOURCE_NOT_FOUND"
	ResourceMismatch                           = "RESOURCE_MISMATCH"
	ResourceAlreadyExists                      = "RESOURCE_ALREADY_EXISTS"
	ResourceNamespaceRequired                  = "RESOURCE_NAMESPACE_REQUIRED"
	ResourceOperationFailed                    = "RESOURCE_OPERATION_FAILED"
	ResourceUnprocessableEntity                = "RESOURCE_UNPROCESSABLE_ENTITY"
	NamespaceNotFound                          = "NAMESPACE_NOT_FOUND"
	InvalidYamlFormat                          = "INVALID_YAML_FORMAT"
	InvalidKeyValueFormat                      = "INVALID_KEY_VALUE_FORMAT"
	PolicyContainsUnauthorizedClusters         = "POLICY_CONTAINS_UNAUTHORIZED_CLUSTERS"
	PolicyMissingTargetClusters                = "POLICY_MISSING_TARGET_CLUSTERS"
	InvalidSortProperty                        = "INVALID_SORT_PROPERTY"
	InvalidSortOrder                           = "INVALID_SORT_ORDER"
	UnsupportedResourceKind                    = "UNSUPPORTED_RESOURCE_KIND"
	UnsupportedPolicyReplicaSchedulingType     = "UNSUPPORTED_POLICY_REPLICA_SCHEDULING_TYPE"
	UnsupportedPolicyReplicaDivisionPreference = "UNSUPPORTED_POLICY_REPLICA_DIVISION_PREFERENCE"
	InvalidPolicyReplicaWeight                 = "INVALID_POLICY_REPLICA_WEIGHT"
	InvalidStaticWeightClusters                = "INVALID_STATIC_WEIGHT_CLUSTERS"
	EmptyStaticWeightClusters                  = "EMPTY_STATIC_WEIGHT_CLUSTERS"
	ClusterRegistrationFailed                  = "CLUSTER_REGISTRATION_FAILED"
	ClusterVerificationFailed                  = "CLUSTER_VERIFICATION_FAILED"
	ClusterMappingSaveFailed                   = "CLUSTER_MAPPING_SAVE_FAILED"
	ClusterLoadConfigFailed                    = "CLUSTER_LOAD_CONFIG_FAILED"
	NotAllowedNamespace                        = "NOT_ALLOWED_NAMESPACE"
)
